apiVersion: apps/v1
kind: Deployment
metadata:
  name: viz-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viz-backend
  template:
    metadata:
      labels:
        app: viz-backend
    spec:
      imagePullSecrets:
        - name: <secret>
      containers:
        - name: viz-backend
          image: <image-name>:<tag>
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: viz-backend-configmap
